### ISSUE TITLE
Web View of this application [ Web App ]

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#20]
**Describe the solution you'd like**
User can access this application on webpage with links

**Comment by SatwikMohan** [comment]
Hi, I am interested to work on this issue.

**Comment by Ijaiswalshivam** [comment]
@SatwikMohan assigned

**Comment by SatwikMohan** [comment]
Hello @Ijaiswalshivam 
For building the web app what shall I proceed with. Shall I move with flutter, KMP or react native.

**Comment by Ijaiswalshivam** [comment]
@SatwikMohan it'll be better with Flutter

**Comment by SatwikMohan** [comment]
Hello @Ijaiswalshivam I have developed the entry screen, the sign up screen and log in screen for the web app in flutter. Shall raise a pull request for the same. I am having doubt regarding the rest of the screens since I don't have access to the firebase account or shall I make my own.

https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/2d06cb3c-674a-48ae-a92c-7bc05aed357b

**Comment by SatwikMohan** [comment]
Hello @Ijaiswalshivam I have developed the entry screen, the sign up screen and log in screen for the web app in flutter. Shall raise a pull request for the same. I am having doubt regarding the rest of the screens since I don't have access to the firebase account or shall I make my own.

https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/2d06cb3c-674a-48ae-a92c-7bc05aed357b

**Comment by Ijaiswalshivam** [comment]
@SatwikMohan you can add your firebase  for the further procedures.

**Comment by Ijaiswalshivam** [comment]
@SatwikMohan what's the current status, by the the time you can also deploy here so that others can also help you by doing contribution.

**Comment by SatwikMohan** [comment]
Hello @Ijaiswalshivam 
Today I will start with the Firebase Integration for the chats screen and authentications.
ok I am raising a pull request.

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by SatwikMohan** [comment]
Hello @Ijaiswalshivam I have pushed the code into my forked repository in the master branch. I have implemented features like SignIn, SignUp, send friend request, accept friend request, show friends. 
The branch does not have anything to compare so I am not able to raise a pull request. Please guide me.

**Comment by Ijaiswalshivam** [comment]
@SatwikMohan Ok.., give me sometime.

**Comment by Ijaiswalshivam** [comment]
@SatwikMohan i had created a talkin webapp folder with .html file, so now you can compare the files

**Comment by SatwikMohan** [comment]
Hello @Ijaiswalshivam  it is still showing nothing to compare. I think a new branch needs to be created where you have to upload the html file because the repository is outside the folder.

**Comment by SatwikMohan** [comment]
@Ijaiswalshivam I want to try once with only html file in the branch Talk-In-WebApp
![Screenshot (474)](https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/8f13450f-57e2-4cb3-97f5-85d7b471150b)

**Comment by Ijaiswalshivam** [comment]
Ok... See

**Comment by Ijaiswalshivam** [comment]
@SatwikMohan see, it may work

**Comment by SatwikMohan** [comment]
![Screenshot (474)](https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/241e8027-f98e-44f4-80ba-dce57e4d549d)
@Ijaiswalshivam  Here is the attachment what I have to do now?

**Comment by Ijaiswalshivam** [comment]
@SatwikMohan I'm adding you as a collaborater, accept the invitation, and try to add file directly on github

**Comment by SatwikMohan** [comment]
@Ijaiswalshivam  I have opened a pull request
